services:
  db-postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ticket_db
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"  # host:container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticket_user -d ticket_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db-postgres:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  postgres_db_data:
